[package]
name = "tasks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { package = "gtk4", version = "0.3.1", features = ["v4_2"]}
adw = { package = "libadwaita", version = "0.1.0-beta-1" }